GET http://localhost:8000/api/v1/posts

###
POST http://localhost:8000/api/v1/create
Content-Type: application/json

{
    "title": "My first post",
    "content": "This is my first post",
    "authorId": 1
}